### ISSUE TITLE
xlsx import

### ISSUE THREAD

**Issue by kkandola1990** [esride-nik/ExB-workshop#1]
Hello, I am a new user to experience builder developer edition and currently trying to use the excel export widget that you have created. I am running into an issue where I receive an error saying that the XLSX import can not be found in 'xlsx'. I am curious to know which xlsx library you are using to make sure that I have the proper library?

**Comment by esride-chb** [comment]
Hello, in the root folder of the repo is a package.json file. There you can find the dependency to the xlsx library. You need to run the command npm install in the root folder, to download and install these dependencies.

**Comment by esride-nik** [comment]
As of a while ago, we moved the dependencies into the widget folders to make it compatible with the production build process. To install all dependencies at once, feel free to execute `npm run install-subfolders` in the client folder.
